In [2]:
import numpy as np

# Load input
filename = 'inputDay16.txt'
# filename = 'inputDay16test.txt'
# filename = 'inputDay16test2.txt'
# curIn = np.loadtxt(filename)

# Start by loading the data
inputFile = open(filename)
inputs = []
inputs = [s for s in inputFile.read().splitlines()]

print('Done loading input')

Done loading input


In [3]:
# Inputs handling
rules = []
yourTicket = ''
nearT = []


numBreak = 0
for k in range(0,len(inputs)):
    
    if (inputs[k] != ''):
        if  (numBreak == 0):
            rules = np.append(rules,inputs[k])
        if (numBreak == 1):
            yourTicket = inputs[k]
        if (numBreak == 2):
            nearT = np.append(nearT,inputs[k])
    else:
        numBreak = numBreak + 1

nearT = nearT[1:]

# print(rules)
# print(yourTicket)
# print(nearT)

In [4]:
print(rules)

['departure location: 34-269 or 286-964'
 'departure station: 27-584 or 609-973'
 'departure platform: 49-135 or 155-974'
 'departure track: 36-248 or 255-954' 'departure date: 50-373 or 381-974'
 'departure time: 49-454 or 472-967' 'arrival location: 33-900 or 925-968'
 'arrival station: 46-699 or 706-965'
 'arrival platform: 42-656 or 666-967' 'arrival track: 49-408 or 425-950'
 'class: 30-626 or 651-957' 'duration: 43-109 or 127-964'
 'price: 33-778 or 795-952' 'route: 37-296 or 315-966'
 'row: 28-318 or 342-965' 'seat: 33-189 or 208-959'
 'train: 49-536 or 552-968' 'type: 46-749 or 772-949'
 'wagon: 29-386 or 401-954' 'zone: 34-344 or 368-954']


In [5]:
RuleNames = []
numRules = len(rules)

# It seems all inputs have two ranges (Never more, never less)
ran1 = []
ran2 = []

min1 = []
max1 = []
min2 = []
max2 = []

for r in rules:
    spl = r.split(': ')
    # print(spl)
    RuleNames = np.append(RuleNames,spl[0])
    rans = spl[1].split(' or ')
    ran1 = np.append(ran1,rans[0])
    ran2 = np.append(ran2,rans[1])
    
    mm1 = rans[0].split('-')
    mm2 = rans[1].split('-')
    min1 = np.append(min1,mm1[0])
    max1 = np.append(max1,mm1[1])
    min2 = np.append(min2,mm2[0])
    max2 = np.append(max2,mm2[1])

min1 = min1.astype(int)
max1 = max1.astype(int)
min2 = min2.astype(int)
max2 = max2.astype(int)

In [6]:
numPas = len(nearT)

validT = np.zeros((0,numRules))

totInvalid = 0
part1sol = 0
for pa in nearT:
    # print(pa)
    paSp = pa.split(',')
    # print(paSp)
    curVals = np.array(paSp).astype(int)
    # print(curVals)

    numInvalid = 0
    for val in curVals:
        # print(val
        anyTrue = False
        for k in range(0,numRules):
            in1 = False
            in2 = False
            
            # print(f'between {min1[k]} and {max1[k]}')
            if ((min1[k] <= val) & (val <= max1[k])):
                in1 = True
            # print(f'between {min2[k]} and {max2[k]}')
            if ((min2[k] <= val) & (val <= max2[k])):
                in2 = True
            # print(f'{in1} and {in2}')

            if (in1 | in2):
                anyTrue = True
            # print(f'So anytrue is: {anyTrue}')
        if (anyTrue == False):
            numInvalid = numInvalid + 1
            part1sol = part1sol + val
    if (numInvalid > 0):
        totInvalid = totInvalid + 1
    else:
        
        validT = np.vstack([validT,curVals])

# print(totInvalid)
print(f'Part 1 solution: {part1sol}')

Part 1 solution: 23122


In [7]:
# # Part 2

# # # Rule has to include "departure"
# # # This i only the 6 first rules, so the rest can be ignored
# # numRulesToUse = 6

# # for k in range(0,numRulesToUse):
# #     print(RuleNames[k])

# # Assumption: Each position is only valid for one field. 
# # Hence, we can simply exclude until only one position is left, and then use that

# # For the test case
# # for k in range(0,numRules):
# for k in range(0,1):
#     # print(f'Checking rule with name: {RuleNames[k]}')
#     posPos = np.ones(numRules)
#     # print(posPos)
#     # Go through the valid tickets
#     # for tic in validT:
#     for t in range(0,len(validT)):
#         tic= validT[t]
#         print(tic)
#         anyTrue = False
#         # for val in tic:
#         for v in range(0,len(tic)):
#             val = tic[v]
#             print(val)
#             in1 = False
#             in2 = False
            
#             print(f'between {min1[k]} and {max1[k]}')
#             if ((min1[k] <= val) & (val <= max1[k])):
#                 in1 = True
#             print(f'between {min2[k]} and {max2[k]}')
#             if ((min2[k] <= val) & (val <= max2[k])):
#                 in2 = True
#             print(f'{in1} and {in2}')

#             if (in1 | in2):
#                 anyTrue = True
#             print(anyTrue)
#             if (anyTrue == False):
#                 posPos[v] = 0

#     print(f'{RuleNames[k]} can be in positions: {posPos}')

In [8]:

allPosPos = np.ones((numRules,numRules))
print(np.arange(0,numRules,1))
for po in range(0,numRules):
# for po in range(0,3):
    # print(f'Checking rule with name: {RuleNames[po]}')
    # print(f'Checking position {po}')
    allValsInPos = []
    posPos = np.ones(numRules)
    # Go through the valid tickets
    for t in range(0,len(validT)):
        tic= validT[t]
        posVal = tic[po]
        allValsInPos = np.append(allValsInPos,posVal)
    # print(allValsInPos)

    posPos = np.ones(numRules)

    for val in allValsInPos:
        # print(f'Value: {val}')
        for k in range(0,numRules):
            in1 = False
            in2 = False
            anyTrue = False
            
            # print(f'Checking rule with name: {RuleNames[k]}')
            # print(f'between {min1[k]} and {max1[k]}')
            if ((min1[k] <= val) & (val <= max1[k])):
                in1 = True
            # print(f'between {min2[k]} and {max2[k]}')
            if ((min2[k] <= val) & (val <= max2[k])):
                in2 = True
            # print(f'{in1} and {in2}')
            if (in1 | in2):
                anyTrue = True
            # print(anyTrue)
            if (anyTrue == False):
                posPos[k] = 0
    # print(f'Possible rules for position {po}:')
    print(f'{posPos} is pos {po}')
    allPosPos[po] = posPos

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0.] is pos 0
[1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.] is pos 1
[1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.] is pos 2
[0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.] is pos 3
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.] is pos 4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0.] is pos 5
[1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.] is pos 6
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0.] is pos 7
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] is pos 8
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.] is pos 9
[0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0.] is pos 10
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] is pos 11
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0.] is pos 12
[0. 0. 0. 0.

In [49]:
ySp = yourTicket.split(',')
# Sudoku solved by hand:
posToUse = [1,19,2,4,14,6]
part2sol = 1
for k in range(0,6):
    part2sol = part2sol * int(ySp[posToUse[k]])
print(part2sol)

362974212989


In [50]:
# Johan's Linear Algebra solution to sudoku
invPos = np.linalg.inv(allPosPos)
solutions = np.where(invPos > 0)
# print(solutions[1])

ruleOrder = dict()
for k in range(0,numRules):
    ruleOrder[k] = solutions[1][k]
# print(ruleOrder)

ruleOrder[5]
posToUse = []
for k in range(0,6):
    posToUse = np.append(posToUse,ruleOrder[k])
# print(posToUse)


ySp = yourTicket.split(',')
part2sol = 1
for k in range(0,6):
    part2sol = part2sol * int(ySp[int(posToUse[k])])
    

print(f'Part 2 solution: {part2sol}')


Part 2 solution: 362974212989


In [320]:

# ruleOrder = dict()
# ruleOrder[13] = 9

# print(ruleOrder)

{13: 9}


In [317]:
# print(allPosPos)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1.

In [238]:
# # Sudoku solving by hand:

# def removeVal(toRmRow,toRmCol,a):
#     # toRm = 13
#     a = np.vstack((a[0:toRmRow],a[toRmRow+1:]))
#     numValLeft = len(a[0]) - 1 

#     b = np.ones((numValLeft,numValLeft))
#     for k in range(0,numValLeft):
#         newA = np.append(a[k][0:toRmCol],a[k][toRmCol+1:])
#         b[k] = newA
#     # print(b)
#     return(b)

# # print(allPosPos[])

{'9': 13}


In [315]:

# a = allPosPos
# # print(a)
# # Position 13 is rule 9
# ruleOrder = dict()
# ruleOrder[9] = 13 
# print(ruleOrder)

{9: 13}


In [316]:
# t = removeVal(13,9,a)
# # print(t1)
# # print(t1[8][13])
# ruleOrder[13] = 8
# t = removeVal(8,13,t)
# # print(t2)
# # print(t2[16][10])
# ruleOrder[10] = 16
# t = removeVal(16,10,t)
# # print(t3)
# # print(t3[5][9])
# ruleOrder[9] = 5
# t = removeVal(5,9,t)


# print(ruleOrder)


{9: 5, 13: 8, 10: 16}


In [305]:
# a = allPosPos.copy()
# curMat = a.copy()

# ruleOrder = dict()
# numRuns = 2
# for run in range(0,numRuns):
#     for k in range(0,len(a)):
#         num1 = sum(a[k])
#         if (num1 == 1):
#             toRmRow = k
#             toRmCol = np.where(a[k] == 1)[0][0]
        
#         # print(t2[16][10])
#         ruleOrder[toRmCol] = toRmRow
#         # print(ruleOrder)
#         newMat = removeVal(toRmRow,toRmCol,a)

#     a = newMat
#     ruleOrder
# # for k in range(0,len(a)):
# #     num1 = sum(a[k])
# #     if (num1 == 1):
# #         toRmRow = k
# #         toRmCol = np.where(a[k] == 1)[0][0]
    
# #     # print(t2[16][10])
# #     ruleOrder[toRmCol] = toRmRow
# #     curMat = removeVal(toRmRow,toRmCol,a)
    
# ruleOrder

{9: 13, 13: 8, 10: 16}