In [71]:
import numpy as np

# Load input
filename = 'inputDay17.txt'
# filename = 'inputDay17test.txt'
# curIn = np.loadtxt(filename)

# Start by loading the data
inputFile = open(filename)
inputs = []
inputs = [s for s in inputFile.read().splitlines()]

print('Done loading input')

Done loading input


In [72]:
# Get the initial state
H = len(inputs)
W = len(inputs[0])
D = 1
curS = np.zeros((H,W,D))

z = D
for x in range(0,W):
    for y in range(0,H):
        if (inputs[x][y] == '#'):
            curS[x,y,0] = 1

ogS = curS.copy()

In [73]:
print('Initial state:')
for z in range(0,D): 
    print(curS[:,:,z])

Initial state:
[[1. 0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 0. 0. 1. 0. 0. 1. 0.]
 [1. 1. 0. 1. 1. 0. 0. 1.]]


In [62]:
def padStateWithZeros(state):
    H,W,D = np.shape(curS)
    newH = H + 2
    newW = W + 2
    newD = D + 2
    
    newState = np.zeros((newH,newW,newD))

    # for x in range(0,newH):
    #     for y in range(0,newW):
    #         for z in range(0,newD):
    for x in range(0,H):
        for y in range(0,W):
            for z in range(0,D):
                if (curS[x,y,z] == 1):
                    newState[x+1,y+1,z+1] = 1
    return newState


newS = padStateWithZeros(curS)


In [63]:

curS = ogS.copy()

numCycles = 6
for k in range(0,numCycles):
    newS = padStateWithZeros(curS)
    # One simulation
    curS = newS 
    H,W,D = np.shape(curS)
    neiArray = np.zeros((H,W,D))
    for x in range(1,H-1):
        for y in range(1,W-1):
            for z in range(1,D-1):

                if (curS[x,y,z] == 1):
                    
                    for nX in range(-1,2):
                        for nY in range(-1,2):
                            for nZ in range(-1,2):
                                neiArray[x+nX,y+nY,z+nZ] = neiArray[x+nX,y+nY,z+nZ] + 1
                    # Remove one, so it doesn't count itself
                    neiArray[x,y,z] = neiArray[x,y,z] - 1

    updS = np.zeros((H,W,D))
    for x in range(0,H):
        for y in range(0,W):
            for z in range(0,D):
                # If a cube is active and exactly 2 or 3 of its neighbors are also active, the cube remains active. Otherwise, the cube becomes inactive.
                # If a cube is inactive but exactly 3 of its neighbors are active, the cube becomes active. Otherwise, the cube remains inactive.
                if (curS[x,y,z] == 1):
                    if ((neiArray[x,y,z] == 2) | (neiArray[x,y,z] == 3)):
                        updS[x,y,z] = 1
                else:
                    if (neiArray[x,y,z] == 3):
                        updS[x,y,z] = 1
    curS = updS

In [65]:
numCubes = 0
for x in range(0,H):
    for y in range(0,W):
        for z in range(0,D):
            if (curS[x,y,z] == 1):
                numCubes = numCubes + 1
print(f'Part 1 solution: {numCubes}')

Part 1 solution: 322


# Part 2: 4D instead of 3D

In [66]:
# Get the initial state
H = len(inputs)
W = len(inputs[0])
D = 1
F = 1
curS = np.zeros((H,W,D,F))

for x in range(0,W):
    for y in range(0,H):
        if (inputs[x][y] == '#'):
            curS[x,y,0,0] = 1

ogS = curS.copy()

(8, 8, 1, 1)


In [67]:
def padStateWithZeros4D(state):
    H,W,D,F = np.shape(curS)
    newH = H + 2
    newW = W + 2
    newD = D + 2
    newF = F + 2
    
    newState = np.zeros((newH,newW,newD,newF))

    # for x in range(0,newH):
    #     for y in range(0,newW):
    #         for z in range(0,newD):
    for x in range(0,H):
        for y in range(0,W):
            for z in range(0,D):
                for q in range(0,F):
                    if (curS[x,y,z,q] == 1):
                        newState[x+1,y+1,z+1,q+1] = 1
    return newState


newS = padStateWithZeros4D(curS)

In [68]:

curS = ogS.copy()

numCycles = 6
for k in range(0,numCycles):
    newS = padStateWithZeros4D(curS)
    # One simulation
    curS = newS 
    H,W,D,F = np.shape(curS)
    neiArray = np.zeros((H,W,D,F))
    for x in range(1,H-1):
        for y in range(1,W-1):
            for z in range(1,D-1):
                for q in range(1,F-1):

                    if (curS[x,y,z,q] == 1):
                        
                        for nX in range(-1,2):
                            for nY in range(-1,2):
                                for nZ in range(-1,2):
                                    for nQ in range(-1,2):
                                    
                                        neiArray[x+nX,y+nY,z+nZ,q+nQ] = neiArray[x+nX,y+nY,z+nZ,q+nQ] + 1
                        # Remove one, so it doesn't count itself
                        neiArray[x,y,z,q] = neiArray[x,y,z,q] - 1

    updS = np.zeros((H,W,D,F))
    for x in range(0,H):
        for y in range(0,W):
            for z in range(0,D):
                for q in range(0,F):
                    # If a cube is active and exactly 2 or 3 of its neighbors are also active, the cube remains active. Otherwise, the cube becomes inactive.
                    # If a cube is inactive but exactly 3 of its neighbors are active, the cube becomes active. Otherwise, the cube remains inactive.
                    if (curS[x,y,z,q] == 1):
                        if ((neiArray[x,y,z,q] == 2) | (neiArray[x,y,z,q] == 3)):
                            updS[x,y,z,q] = 1
                    else:
                        if (neiArray[x,y,z,q] == 3):
                            updS[x,y,z,q] = 1
    curS = updS

In [69]:
numCubes = 0
for x in range(0,H):
    for y in range(0,W):
        for z in range(0,D):
            for q in range(0,F):
                if (curS[x,y,z,q] == 1):
                    numCubes = numCubes + 1
print(f'Part 2 solution: {numCubes}')

Part 2 solution: 2000
