In [8]:
import numpy as np

timeStamp = 939
buses =[7,13,59,31,19]
timeStamp = 1001171
buses = [17,41,37,367,19,23,29,613,13]
# buses = np.array([7,13,59,31,19])
timeStamp = 939
busesRaw = '7,13,x,x,59,x,31,19'
timeStamp = 1001171
busesRaw = '17,x,x,x,x,x,x,41,x,x,x,37,x,x,x,x,x,367,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,19,x,x,x,23,x,x,x,x,x,29,x,613,x,x,x,x,x,x,x,x,x,x,x,x,13'
# busesRaw = '17,x,13,19'
# busesRaw = '67,7,x,59,61'
# busesRaw = '1789,37,47,1889'

In [9]:
# Get buses for part 1
busesSplit = busesRaw.split(',')
buses = []
for k in range(0,len(busesSplit)):
    if (busesSplit[k] != 'x'):
        buses = np.append(buses,int(busesSplit[k]))
print(buses)
buses = buses.astype(int)
print(buses)

[ 17.  41.  37. 367.  19.  23.  29. 613.  13.]
[ 17  41  37 367  19  23  29 613  13]


In [10]:
# Part 1
newTimes = []
for k in range(0,len(buses)):
    curBus = buses[k]
    timeSinceBus = timeStamp % curBus
    newTime = timeStamp - timeSinceBus + curBus
    newTimes = np.append(newTimes,newTime)

minID = np.argmin(newTimes)
part1sol = (newTimes[minID] - timeStamp) * buses[minID]
print(f'Part 1 solution: {part1sol}')

Part 1 solution: 1835.0


In [11]:
buses = []
busOrders = []
busOrdersFull = []
curBusOrder = 0
for k in range(0,len(busesSplit)):
    if (busesSplit[k] != 'x'):
        # buses = np.append(buses,int(busesSplit[k]))
        buses = np.append(buses,np.int64(busesSplit[k]))
        busOrders = np.append(busOrders,curBusOrder)
        
    busOrdersFull = np.append(busOrdersFull,curBusOrder)
    curBusOrder = curBusOrder +1
    
# buses = buses.astype(int)
print(buses)
print(busOrders)


[ 17.  41.  37. 367.  19.  23.  29. 613.  13.]
[ 0.  7. 11. 17. 36. 40. 46. 48. 61.]


In [35]:
# Part 2, pretty solution
maxVal = 1000000000000000
k = 1
curInc = 1
nextBus = 0
while (k < maxVal):

    
    if (((k + busOrders[nextBus]) % buses[nextBus]) == 0):
        curInc = curInc * buses[nextBus]
        nextBus = nextBus + 1
        part2sol = int(k)
        print(f'First time that the {nextBus} first buses fulfill criteria is at time {int(k)}')

    k = k + curInc

print(f'Part 2 solution: {part2sol}')

First time that the 1 first buses fulfill criteria is at time 17
First time that the 2 first buses fulfill criteria is at time 34
First time that the 3 first buses fulfill criteria is at time 18156
First time that the 4 first buses fulfill criteria is at time 2932313
First time that the 5 first buses fulfill criteria is at time 107042506
First time that the 6 first buses fulfill criteria is at time 1186002688
First time that the 7 first buses fulfill criteria is at time 121130409587
First time that the 8 first buses fulfill criteria is at time 26508899927367
First time that the 9 first buses fulfill criteria is at time 247086664214628
Part 2 solution: 247086664214628


In [36]:
# Part 2, stupid implementation of pretty solution
maxVal = 1000000000000000
k = np.int64(1)
curInc = np.int64(1)
while (k < maxVal):
    if (((k + busOrders[0]) % buses[0]) == 0):
        curInc = buses[0]
        
        if (((k + busOrders[1]) % buses[1]) == 0):
            curInc = curInc * buses[1]
            
            if (((k + busOrders[2]) % buses[2]) == 0):
                curInc = curInc * buses[2]
                
                if (((k + busOrders[3]) % buses[3]) == 0):
                    curInc = curInc * buses[3]
                        
                    if (((k + busOrders[4]) % buses[4]) == 0):
                        curInc = curInc * buses[4]
                        
                        if (((k + busOrders[5]) % buses[5]) == 0):
                            curInc = curInc * buses[5]

                            if (((k + busOrders[6]) % buses[6]) == 0):
                                curInc = curInc * buses[6]
                                
                                if (((k + busOrders[7]) % buses[7]) == 0):
                                    curInc = curInc * buses[7] 
                                    
                                    if (((k + busOrders[8]) % buses[8]) == 0):
                                        curInc = curInc * buses[8]
                                        
                                        print(f'Part 2 solution: {np.int64(k)}')
    k = k + curInc


Part 2 solution: 247086664214628
