In [1]:
import numpy as np

# Load input
filename = 'inputDay10.txt'
filename = 'inputDay10test.txt'
# filename = 'inputDay10test2.txt'
# curIn = np.loadtxt(filename)

# Start by loading the data
inputFile = open(filename)
inputs = []
inputs = [s for s in inputFile.read().splitlines()]

print('Done loading input')

Done loading input


In [2]:
# print(inputs)
inArray = np.array(inputs).astype(np.int)
print(inArray)

[16 10 15  5  1 11  7 19  6 12  4]


In [3]:
ar = np.sort(inArray)

# Add 0 and 3+max
curMax = max(ar)
ar = np.append(ar,curMax+3)
ar = np.append(0,ar)

print(ar)

di = ar[1:] - ar[0:-1]
di
print(di)

num1 = sum(di==1)
num3 = sum(di==3)

print('Part 1 solution: '+str(num1*num3))

[ 0  1  4  5  6  7 10 11 12 15 16 19 22]
[1 3 1 1 1 3 1 1 3 1 3 3]
Part 1 solution: 35


In [4]:
# Part 2

# Naive idea: a depth-first search kind of thing? Go through the list, hope that its not too slow
 

# stillSearch = True
# curIndex = 0

# allChains = []
# curChain = []
# while stillSearch:
#     curVal = ar[curIndex]
#     print(curVal)
#     curChain = np.append(curChain,curVal)
#     print(curChain)

#     posVals = [curVal+1,curVal+2,curVal+3]
#     posIndex = np.nonzero(np.in1d(ar,posVals))
    
#     print(ar[posIndex])

#     curIndex = curIndex + 1
    
#     if (curIndex == len(ar)-1):
#         stillSearch = False

print(ar)
curChain = ar[0:1]

numFoundTotal = 0
# Functionalize
# def goDeeper(chain,curIndex):
def goDeeper(chain,numFoundTotal):

    curVal = chain[-1] 
    print(curVal)
    posVals = [curVal+1,curVal+2,curVal+3]
    print(posVals)
    posIndex = np.nonzero(np.in1d(ar,posVals))[0]
    print(ar[posIndex])
    print(len(posIndex))

    for k in range(0,len(posIndex)):
        newChain = np.append(chain,ar[posIndex[k]])
        print(newChain)

        chain=newChain

        print(chain)
        if (chain[-1] == ar[-1]):
            print('done')
            numFoundTotal = numFoundTotal + 1
            return(chain,numFoundTotal)
        else:
            chain,numFoundTotal = goDeeper(chain,numFoundTotal) 
            return(chain,numFoundTotal)

    # if (len(posIndex) == 1):
        
    #     chain = np.append(chain,ar[posIndex])
    #     # return(chain)
    # if (len(posIndex) == 2):
    #     newChains = []
    #     chain1 = np.append(chain,ar[posIndex[0]])
    #     chain2 = np.append(chain,ar[posIndex[1]])

    #     newChains = np.append(newChains,[chain1])
    #     newChains = np.append(newChains,[chain2])

    #     print(newChains)
    #     # return(chain1)
    # if (len(posIndex) == 3):
    #     newChains = []
    #     chain1 = np.append(chain,ar[posIndex[0]])
    #     chain2 = np.append(chain,ar[posIndex[1]])
    #     chain3 = np.append(chain,ar[posIndex[2]])

    #     newChains = np.append(newChains,[chain1])
    #     newChains = np.append(newChains,[chain2])
    #     newChains = np.append(newChains,[chain3])

    #     print(newChains)
        # return(chain1)

print(numFoundTotal)
curChain,numFoundTotal= goDeeper(curChain,numFoundTotal)
# for k in range(0,10):
    # curChain = goDeeper(curChain)
    # print(curChain)
# print(goDeeper(goDeeper(curChain)))
print('Part 2 solution: '+str(numFoundTotal))

[ 0  1  4  5  6  7 10 11 12 15 16 19 22]
0
0
[1, 2, 3]
[1]
1
[0 1]
[0 1]
1
[2, 3, 4]
[4]
1
[0 1 4]
[0 1 4]
4
[5, 6, 7]
[5 6 7]
3
[0 1 4 5]
[0 1 4 5]
5
[6, 7, 8]
[6 7]
2
[0 1 4 5 6]
[0 1 4 5 6]
6
[7, 8, 9]
[7]
1
[0 1 4 5 6 7]
[0 1 4 5 6 7]
7
[8, 9, 10]
[10]
1
[ 0  1  4  5  6  7 10]
[ 0  1  4  5  6  7 10]
10
[11, 12, 13]
[11 12]
2
[ 0  1  4  5  6  7 10 11]
[ 0  1  4  5  6  7 10 11]
11
[12, 13, 14]
[12]
1
[ 0  1  4  5  6  7 10 11 12]
[ 0  1  4  5  6  7 10 11 12]
12
[13, 14, 15]
[15]
1
[ 0  1  4  5  6  7 10 11 12 15]
[ 0  1  4  5  6  7 10 11 12 15]
15
[16, 17, 18]
[16]
1
[ 0  1  4  5  6  7 10 11 12 15 16]
[ 0  1  4  5  6  7 10 11 12 15 16]
16
[17, 18, 19]
[19]
1
[ 0  1  4  5  6  7 10 11 12 15 16 19]
[ 0  1  4  5  6  7 10 11 12 15 16 19]
19
[20, 21, 22]
[22]
1
[ 0  1  4  5  6  7 10 11 12 15 16 19 22]
[ 0  1  4  5  6  7 10 11 12 15 16 19 22]
done
Part 2 solution: 1


In [5]:
# totCount = 1
# print(ar[0:-6])
# for k in range(0,len(ar)-7):    
#     curVal = ar[k] 
#     print(curVal)
#     posVals = [curVal+1,curVal+2,curVal+3]
#     # print(posVals)
#     posIndex = np.nonzero(np.in1d(ar,posVals))[0]
    
#     print('asdf'+str(len(posIndex)))
#     # totCount = totCount * len(posIndex)
#     totCount = totCount * len(posIndex)
# print(totCount)

In [17]:
# curChain = ar[0:1]

# def newFunc(index,numToAdd):

#     # print('index '+str(index))
#     curVal = ar[index]  
#     print('curVal '+str(curVal))
#     posVals = [curVal+1,curVal+2,curVal+3]
#     print('posVals '+str(posVals))
#     posIndex = np.nonzero(np.in1d(ar,posVals))[0]

#     # print('posIndex '+str(posIndex))
#     foundVals = ar[posIndex]
#     print('foundVals '+str(foundVals))
    
#     # newChain = np.appendchain
#     # newFunc(chain) 
#     for k in range(0,len(posIndex)):
#         newFunc(posIndex[k],0)
        


# part2Solution = newFunc(0,0)

In [32]:
def checkChain(chain):
    dif = chain[1:] - chain[0:-1]
    # print(dif)
    # print(dif>3) 
    if any(dif > 3):
        return False
    else:
        return True


numFound = 1
# Remove 1
for k in range(1,len(ar)-1):
    newChain = np.append(ar[0:k],ar[k+1:])
    if checkChain(newChain):
        numFound = numFound + 1
    # Remove 2
    for j in range(1,len(newChain)-1):
        newnewChain = np.append(newChain[0:j],newChain[j+1:])
        print(newnewChain)
        print(checkChain(newnewChain))
        if checkChain(newnewChain):
            numFound = numFound + 1
print(numFound)

[ 0  5  6  7 10 11 12 15 16 19 22]
False
[ 0  4  6  7 10 11 12 15 16 19 22]
False
[ 0  4  5  7 10 11 12 15 16 19 22]
False
[ 0  4  5  6 10 11 12 15 16 19 22]
False
[ 0  4  5  6  7 11 12 15 16 19 22]
False
[ 0  4  5  6  7 10 12 15 16 19 22]
False
[ 0  4  5  6  7 10 11 15 16 19 22]
False
[ 0  4  5  6  7 10 11 12 16 19 22]
False
[ 0  4  5  6  7 10 11 12 15 19 22]
False
[ 0  4  5  6  7 10 11 12 15 16 22]
False
[ 0  5  6  7 10 11 12 15 16 19 22]
False
[ 0  1  6  7 10 11 12 15 16 19 22]
False
[ 0  1  5  7 10 11 12 15 16 19 22]
False
[ 0  1  5  6 10 11 12 15 16 19 22]
False
[ 0  1  5  6  7 11 12 15 16 19 22]
False
[ 0  1  5  6  7 10 12 15 16 19 22]
False
[ 0  1  5  6  7 10 11 15 16 19 22]
False
[ 0  1  5  6  7 10 11 12 16 19 22]
False
[ 0  1  5  6  7 10 11 12 15 19 22]
False
[ 0  1  5  6  7 10 11 12 15 16 22]
False
[ 0  4  6  7 10 11 12 15 16 19 22]
False
[ 0  1  6  7 10 11 12 15 16 19 22]
False
[ 0  1  4  7 10 11 12 15 16 19 22]
True
[ 0  1  4  6 10 11 12 15 16 19 22]
False
[ 0  1  4  6  7 1